baseURL = "https://openstack-devs.github.io/openstack-devs/"
languageCode = "en-us"
title = "My Hugo Blog"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  ShowReadingTime = true
  ShowCodeCopyButtons = true

